# -*- mode: ruby -*-
# vi: set ft=ruby :

require '../Common.rb'


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. For a complete reference,
  # please see the online documentation at vagrantup.com.

  include Common


  BASTION_IP = isEmpty(ENV['WEBSERVER_IP']) ? '192.168.10.2' : ENV['BASTION_IP']
  WEBSERVER_IP = isEmpty(ENV['WEBSERVER_IP']) ? '192.168.10.3' : ENV['WEBSERVER_IP']

  config.vm.boot_timeout = 600;

  config.vm.define "bastion" do |bastion|
    # Every Vagrant virtual environment requires a box to build off of.
    bastion.vm.box = DEFAULT_VAGRANT_BOX

    # Create a private network that allows host-only access to the machine using a specific IP.
    puts "----- Server IP set to #{BASTION_IP} "
    bastion.vm.network "private_network", :ip => BASTION_IP

    puts "----- Mount #{CHEF_SOURCE_PATH} to #{PROJECT_CHEF_HOME}"
    bastion.vm.synced_folder "#{SOURCE_PATH}/chef", PROJECT_CHEF_HOME, 
        create: true,  owner: "root", group: "root"

     bastion.vm.provision "shell" do | s |
        s.path = "#{CHEF_SOURCE_PATH}/bin/run-chef.sh"
        s.args = ["/vagrant/bastion.json", "--yum-suppress", "--log-stdout"]
     end

  end

  config.vm.define "webserver" do |webserver|
    # Every Vagrant virtual environment requires a box to build off of.
    webserver.vm.box = DEFAULT_VAGRANT_BOX

    # Create a private network that allows host-only access to the machine using a specific IP.
    puts "----- Server IP set to #{WEBSERVER_IP} "
    webserver.vm.network "private_network", :ip => WEBSERVER_IP

    puts "----- Mount #{CHEF_SOURCE_PATH} to #{PROJECT_CHEF_HOME}"
    webserver.vm.synced_folder "#{SOURCE_PATH}/chef", PROJECT_CHEF_HOME, 
        create: true,  owner: "root", group: "root"

     webserver.vm.provision "shell" do | s |
        s.path = "#{CHEF_SOURCE_PATH}/bin/run-chef.sh"
        s.args = ["/vagrant/webserver.json", "--yum-suppress", "--log-stdout"]
     end

  end
end
